name: Docker Image CD

on:
  workflow_run: 
    workflows: ["Back & Front CI"]
    types:
      - completed
    branches: ["main"]

jobs:
  back-docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and Push back docker
      uses: docker/build-push-action@v7
      with:
        context: ./back
        push: true
        tags: xqal/back:latest

  front-docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build and Push front docker
      uses: docker/build-push-action@v7
      with:
        context: ./front
        push: true
        tags: xqal/front:latest
        
